# view vs copy===>

In [3]:
import numpy as np
a = np.array([10,20,30,40,])
b = a[1:3]
b[:] = 0
a

array([10,  0,  0, 40])

In [4]:
a = np.array([10,20,30,40,50,60])
b = a[1:3].copy() 
b[:] = 0 
b
a

array([10, 20, 30, 40, 50, 60])

In [5]:
# LinSpace() ===> It returns same gap numbers from minimum number to maximum number . 
a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])