In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
a = [1,23,25,76]
type(a)

list

In [4]:
b = np.array(a)
b

array([ 1, 23, 25, 76])

In [5]:
type(b)

numpy.ndarray

# how can we create user defined array?

In [6]:
a=[]
size = int(input("Enter size:"))
for i in range(size):
    val = int(input("Enter Number:"))
    a.append(val)

b = np.array(a)
b

Enter size: 2
Enter Number: 32
Enter Number: 35


array([32, 35])

In [15]:
a = [1,2,3]
b = np.array(a)
b

array([1, 2, 3])

# Shape,size,dimension of an array

In [7]:
print("Total shape = ",b.shape)
print("Total elementes = ",b.size)
print("Total Dimension = ",b.ndim)

Total shape =  (3,)
Total elementes =  3
Total Dimension =  1


In [8]:
a = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
print("Total shape = ",b.shape)
print("Total elementes = ",b.size)
print("Total Dimension = ",b.ndim)

Total shape =  (3, 3)
Total elementes =  9
Total Dimension =  2


# Pre-defined functions in Numpy

# (1).zeros()====>This will craete an array in which the values are 0.

In [10]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [12]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# (2).ones ()===>it will crate an array in which all the values are 1.

In [13]:
a=np.ones(3)
a

array([1., 1., 1.])

In [16]:
a = np.ones((4,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# 3.eye()===> it will crate an array in which diognal positional elementes are 1 and rest all are 0.

In [18]:
a = np.eye(3,4)  ### n(row) != n(columns)  ====> ASymmatric Matrix 
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [17]:
a=np.eye(4)  #### n(row) = n(column)  ====> Symmatric Matrix
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# 4.diag()===>it will customize our diognal positional values.

In [21]:
a = np.diag([1,22,54,65])
a

array([[ 1,  0,  0,  0],
       [ 0, 22,  0,  0],
       [ 0,  0, 54,  0],
       [ 0,  0,  0, 65]])

In [19]:
# (5). Random Module ====> 
# (a). Randint() ===> It will create an array from min_range to max_range . 
# syntax : np.random.randint(min_vaue , max_value , total_numbers) 

a = np.random.randint(1,10,3)
a

array([3, 2, 5])

In [24]:
#(b). Rand ===> it will create an array in which all the values belong from 0 to 1.
#syntax : np.random.rand(total_numbers)

a = np.random.rand (4)
a

array([0.24224129, 0.3931351 , 0.50334104, 0.44135625])

In [7]:
#(c). seed()===>
np.random.seed(67)
a = np.random.randint(1,10,3)
a


array([4, 6, 6])