In [1]:
#Reshaping Array

In [14]:
import numpy as np

In [15]:
a = np.random.randint(1,50,12)
a

array([ 8, 30, 26,  7, 30,  8, 39, 13,  9,  6, 29, 29])

In [16]:
# reshape ===> n(rows) x n(columns) =n(total_elementes)

In [18]:
a.reshape(2,6)

array([[ 8, 30, 26,  7, 30,  8],
       [39, 13,  9,  6, 29, 29]])

In [19]:
a.reshape(3,4)

array([[ 8, 30, 26,  7],
       [30,  8, 39, 13],
       [ 9,  6, 29, 29]])

In [20]:
a = np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [21]:
b = np.array([5,6,7,8]).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [22]:
a+b ### 1+5= 6, 2+6=8, 3+7=10, 4+8=12

array([[ 6,  8],
       [10, 12]])

In [23]:
a-b

array([[-4, -4],
       [-4, -4]])

In [24]:
a.dot(b)    ###return matrix multiplication

array([[19, 22],
       [43, 50]])

In [25]:
#unique() ===> Return unique values

In [26]:
a = np.array([10,20,30,10,10,10,10,40,50,10,30,10,10])
np.unique(a, return_index = True, return_counts = True)

(array([10, 20, 30, 40, 50]),
 array([0, 1, 2, 7, 8], dtype=int64),
 array([8, 1, 2, 1, 1], dtype=int64))

In [26]:
#stacking ===>
# (a). Hstack() ===> combines 2 or matrix in horizontally.
# (b). vstack() ===> combines or more in vertically.

In [29]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([9,10,11,12])

In [31]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [32]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Pandas

In [33]:
#open-Source Library that is used for handle data manipulations.

In [3]:
import pandas as pd

In [4]:
# Data Structure ===>
# (a). Series ===> 1-D Data . it contaund only values not include column name.
# (b). DataFrame ===> multi-dimenstional data. it cntains values with column name.

# Series

In [5]:
a = pd.Series([1,45,78,90])
a

0     1
1    45
2    78
3    90
dtype: int64

In [6]:
type(a)

pandas.core.series.Series

 # DataFrame

In [7]:
a = {
    "Emp_ID":['A' , 'B' , 'C' , 'D' , 'E' , 'F'],
    "Name" : ['Sam' , 'Mohit' , 'Raj' , 'Rahul' , 'Gorav' , 'Aniket'],
    "Department":['IT' , 'HR' , 'HR' , 'IT' , 'IT' , 'Sales'],
    "Salary" : [23000 , 26000 , 34000 , 56000 , 40000 , 53000]
}

In [8]:
type(a) 

dict

In [9]:
df = pd.DataFrame(a) 
df

Emp_ID    Name Department  Salary
0      A     Sam         IT   23000
1      B   Mohit         HR   26000
2      C     Raj         HR   34000
3      D   Rahul         IT   56000
4      E   Gorav         IT   40000
5      F  Aniket      Sales   53000

In [10]:
type(df) 

pandas.core.frame.DataFrame

# How can we check top data in a dataframe ? 

In [11]:
# df.head() 

In [13]:
 #df.head(3) 

# How can we check bottom data in a dataframe ? 

In [52]:
# df.tail() 

In [53]:
# df.tail(2)

# How can we check random indexed data ? 

In [54]:
# df.sample() 

In [55]:
df.sample(2) 

Emp_ID   Name Department  Salary
1      B  Mohit         HR   26000
4      E  Gorav         IT   40000

# How can we check total data shape ? 

In [56]:
# df.shape 

# How can we check total columns in a dataframe ? 

In [57]:
# df.columns 

# How can we check total sub-categories of a column ? 

In [58]:
# df['Department'].value_counts() 

# How  can we check overall information of data ? 

In [59]:
# df.info() 

# How can we check statically view of a data ? 

In [60]:
# df.describe() 

In [61]:
# DataFrmae is mutable . 

In [62]:
# df

In [63]:
# df['Name'][2] = "Pallavi"

In [64]:
# df

In [65]:
# loc() and iloc()  ====> 

df.loc[1:3 , ['Name' , 'Salary']]    #### df.loc[row_range , column_name]

Name  Salary
1  Mohit   26000
2    Raj   34000
3  Rahul   56000

In [66]:
df.iloc[1:4 , [0,1,2,3]]    #### df.iloc[row_range , column_range]

Emp_ID   Name Department  Salary
1      B  Mohit         HR   26000
2      C    Raj         HR   34000
3      D  Rahul         IT   56000